//! Static nation metadata for procedural world generation (World Scale-Up Phase A).
//!
//! 50 real nations (geographic data, not IP), each with a hand-tiered
//! `nation_power` (UEFA-coefficient-style hierarchy — same tiers in every
//! world, NOT seed-driven), a club-naming style, and a pool of city names
//! that the genesis-time club-name generator draws from.
//!
//! This table is the "authoring-time data" of Bible §7.2: it can be enriched
//! offline (e.g. by an LLM authoring pass emitting the same schema) without
//! touching runtime code.

/// Club-naming flavor family. Patterns are football-generic forms
/// ("X United", "Real X", "AC X"...) combined with city names.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NameStyle {
    English,
    Spanish,
    Portuguese,
    German,
    Italian,
    French,
    Dutch,
    Generic,
}

/// One nation's static definition.
pub struct NationDef {
    pub name: &'static str,
    /// 1–99, hand-assigned by tier (decision 4 in docs/WORLD-SCALE-UP.md).
    pub power: u8,
    /// Number of divisions in this nation's pyramid (3 or 4).
    pub divisions: u8,
    pub style: NameStyle,
    /// City pool for club names. 12+ cities × 8 patterns >= 64 unique names,
    /// enough for the largest pyramid (4 divisions × 16 clubs).
    pub cities: &'static [&'static str],
}

use NameStyle::*;

/// Tier 1 (elite leagues): 4 divisions each.
const T1_DIVS: u8 = 4;
/// Tier 2 (South-American giants + Portugal/Netherlands): 4 divisions.
const T2_DIVS: u8 = 4;
/// Tiers 3–5: 3 divisions.
const T3_DIVS: u8 = 3;

/// The fixed 50-nation list (decision 3: fixed, not seed-driven).
/// Ordered by tier then power, for readability — generation does not depend
/// on the order.
pub static NATIONS: &[NationDef] = &[
    // ── Tier 1: elite (90–95) ────────────────────────────────────────────────
    NationDef {
        name: "England",
        power: 95,
        divisions: T1_DIVS,
        style: English,
        cities: &[
            "Manchester",
            "Liverpool",
            "Leeds",
            "Newcastle",
            "Birmingham",
            "Sheffield",
            "Bristol",
            "Nottingham",
            "Leicester",
            "Southampton",
            "Brighton",
            "Norwich",
        ],
    },
    NationDef {
        name: "Spain",
        power: 94,
        divisions: T1_DIVS,
        style: Spanish,
        cities: &[
            "Madrid",
            "Barcelona",
            "Sevilla",
            "Valencia",
            "Bilbao",
            "Zaragoza",
            "Málaga",
            "Valladolid",
            "Vigo",
            "Santander",
            "Granada",
            "Cádiz",
        ],
    },
    NationDef {
        name: "Germany",
        power: 93,
        divisions: T1_DIVS,
        style: German,
        cities: &[
            "Munich",
            "Dortmund",
            "Hamburg",
            "Stuttgart",
            "Frankfurt",
            "Köln",
            "Leipzig",
            "Bremen",
            "Hannover",
            "Nürnberg",
            "Freiburg",
            "Bochum",
        ],
    },
    NationDef {
        name: "Italy",
        power: 91,
        divisions: T1_DIVS,
        style: Italian,
        cities: &[
            "Milan", "Rome", "Turin", "Naples", "Florence", "Bologna", "Genoa", "Verona", "Parma",
            "Bari", "Palermo", "Cagliari",
        ],
    },
    NationDef {
        name: "France",
        power: 90,
        divisions: T1_DIVS,
        style: French,
        cities: &[
            "Paris",
            "Lyon",
            "Marseille",
            "Lille",
            "Bordeaux",
            "Nantes",
            "Rennes",
            "Toulouse",
            "Nice",
            "Strasbourg",
            "Metz",
            "Le Havre",
        ],
    },
    // ── Tier 2: giants outside the big-5 (84–88) ─────────────────────────────
    NationDef {
        name: "Brazil",
        power: 88,
        divisions: T2_DIVS,
        style: Portuguese,
        cities: &[
            "São Paulo",
            "Rio de Janeiro",
            "Belo Horizonte",
            "Porto Alegre",
            "Salvador",
            "Recife",
            "Fortaleza",
            "Curitiba",
            "Santos",
            "Campinas",
            "Manaus",
            "Natal",
        ],
    },
    NationDef {
        name: "Argentina",
        power: 86,
        divisions: T2_DIVS,
        style: Spanish,
        cities: &[
            "Buenos Aires",
            "Rosario",
            "Córdoba",
            "Mendoza",
            "La Plata",
            "Tucumán",
            "Santa Fe",
            "Salta",
            "Mar del Plata",
            "Bahía Blanca",
            "Paraná",
            "Neuquén",
        ],
    },
    NationDef {
        name: "Portugal",
        power: 85,
        divisions: T2_DIVS,
        style: Portuguese,
        cities: &[
            "Lisbon",
            "Porto",
            "Braga",
            "Coimbra",
            "Faro",
            "Setúbal",
            "Aveiro",
            "Guimarães",
            "Leiria",
            "Évora",
            "Funchal",
            "Viseu",
        ],
    },
    NationDef {
        name: "Netherlands",
        power: 84,
        divisions: T2_DIVS,
        style: Dutch,
        cities: &[
            "Amsterdam",
            "Rotterdam",
            "Eindhoven",
            "Utrecht",
            "Groningen",
            "Arnhem",
            "Tilburg",
            "Breda",
            "Zwolle",
            "Maastricht",
            "Alkmaar",
            "Haarlem",
        ],
    },
    // ── Tier 3: strong second-rank nations (73–80) ───────────────────────────
    NationDef {
        name: "Belgium",
        power: 80,
        divisions: T3_DIVS,
        style: Dutch,
        cities: &[
            "Brussels",
            "Antwerp",
            "Ghent",
            "Bruges",
            "Liège",
            "Leuven",
            "Genk",
            "Mechelen",
            "Charleroi",
            "Kortrijk",
            "Ostend",
            "Mons",
        ],
    },
    NationDef {
        name: "Croatia",
        power: 78,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Zagreb",
            "Split",
            "Rijeka",
            "Osijek",
            "Zadar",
            "Pula",
            "Šibenik",
            "Varaždin",
            "Dubrovnik",
            "Karlovac",
            "Slavonski Brod",
            "Vinkovci",
        ],
    },
    NationDef {
        name: "Uruguay",
        power: 77,
        divisions: T3_DIVS,
        style: Spanish,
        cities: &[
            "Montevideo",
            "Salto",
            "Paysandú",
            "Maldonado",
            "Rivera",
            "Colonia",
            "Tacuarembó",
            "Melo",
            "Rocha",
            "Florida",
            "Durazno",
            "Minas",
        ],
    },
    NationDef {
        name: "Colombia",
        power: 76,
        divisions: T3_DIVS,
        style: Spanish,
        cities: &[
            "Bogotá",
            "Medellín",
            "Cali",
            "Barranquilla",
            "Cartagena",
            "Bucaramanga",
            "Pereira",
            "Cúcuta",
            "Ibagué",
            "Manizales",
            "Neiva",
            "Pasto",
        ],
    },
    NationDef {
        name: "Mexico",
        power: 75,
        divisions: T3_DIVS,
        style: Spanish,
        cities: &[
            "Mexico City",
            "Guadalajara",
            "Monterrey",
            "Puebla",
            "Tijuana",
            "León",
            "Mérida",
            "Toluca",
            "Veracruz",
            "Querétaro",
            "Morelia",
            "Chihuahua",
        ],
    },
    NationDef {
        name: "USA",
        power: 74,
        divisions: T3_DIVS,
        style: English,
        cities: &[
            "Los Angeles",
            "New York",
            "Chicago",
            "Houston",
            "Miami",
            "Seattle",
            "Atlanta",
            "Denver",
            "Portland",
            "Dallas",
            "Boston",
            "Phoenix",
        ],
    },
    NationDef {
        name: "Japan",
        power: 74,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Tokyo",
            "Osaka",
            "Yokohama",
            "Nagoya",
            "Sapporo",
            "Fukuoka",
            "Hiroshima",
            "Sendai",
            "Kyoto",
            "Kobe",
            "Niigata",
            "Okayama",
        ],
    },
    NationDef {
        name: "South Korea",
        power: 73,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Seoul",
            "Busan",
            "Incheon",
            "Daegu",
            "Daejeon",
            "Gwangju",
            "Suwon",
            "Ulsan",
            "Jeonju",
            "Pohang",
            "Gangneung",
            "Jeju",
        ],
    },
    // ── Tier 4: solid footballing nations (58–72) ────────────────────────────
    NationDef {
        name: "Turkey",
        power: 72,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Istanbul",
            "Ankara",
            "Izmir",
            "Bursa",
            "Antalya",
            "Adana",
            "Trabzon",
            "Konya",
            "Gaziantep",
            "Kayseri",
            "Samsun",
            "Denizli",
        ],
    },
    NationDef {
        name: "Switzerland",
        power: 70,
        divisions: T3_DIVS,
        style: German,
        cities: &[
            "Zurich",
            "Basel",
            "Geneva",
            "Bern",
            "Lausanne",
            "Lucerne",
            "Lugano",
            "Sion",
            "St. Gallen",
            "Thun",
            "Winterthur",
            "Aarau",
        ],
    },
    NationDef {
        name: "Austria",
        power: 69,
        divisions: T3_DIVS,
        style: German,
        cities: &[
            "Vienna",
            "Salzburg",
            "Graz",
            "Linz",
            "Innsbruck",
            "Klagenfurt",
            "St. Pölten",
            "Wels",
            "Steyr",
            "Villach",
            "Bregenz",
            "Eisenstadt",
        ],
    },
    NationDef {
        name: "Denmark",
        power: 68,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Copenhagen",
            "Aarhus",
            "Odense",
            "Aalborg",
            "Esbjerg",
            "Randers",
            "Kolding",
            "Horsens",
            "Vejle",
            "Roskilde",
            "Silkeborg",
            "Viborg",
        ],
    },
    NationDef {
        name: "Scotland",
        power: 68,
        divisions: T3_DIVS,
        style: English,
        cities: &[
            "Glasgow",
            "Edinburgh",
            "Aberdeen",
            "Dundee",
            "Inverness",
            "Perth",
            "Stirling",
            "Ayr",
            "Kilmarnock",
            "Falkirk",
            "Paisley",
            "Dumfries",
        ],
    },
    NationDef {
        name: "Poland",
        power: 67,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Warsaw",
            "Kraków",
            "Gdańsk",
            "Wrocław",
            "Poznań",
            "Łódź",
            "Szczecin",
            "Lublin",
            "Katowice",
            "Bydgoszcz",
            "Białystok",
            "Toruń",
        ],
    },
    NationDef {
        name: "Greece",
        power: 66,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Athens",
            "Thessaloniki",
            "Patras",
            "Larissa",
            "Heraklion",
            "Volos",
            "Ioannina",
            "Rhodes",
            "Chania",
            "Kavala",
            "Kalamata",
            "Serres",
        ],
    },
    NationDef {
        name: "Chile",
        power: 66,
        divisions: T3_DIVS,
        style: Spanish,
        cities: &[
            "Santiago",
            "Valparaíso",
            "Concepción",
            "Antofagasta",
            "Temuco",
            "La Serena",
            "Iquique",
            "Valdivia",
            "Puerto Montt",
            "Rancagua",
            "Talca",
            "Chillán",
        ],
    },
    NationDef {
        name: "Sweden",
        power: 66,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Stockholm",
            "Gothenburg",
            "Malmö",
            "Uppsala",
            "Linköping",
            "Örebro",
            "Västerås",
            "Norrköping",
            "Helsingborg",
            "Umeå",
            "Gävle",
            "Borås",
        ],
    },
    NationDef {
        name: "Czechia",
        power: 66,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Prague",
            "Brno",
            "Ostrava",
            "Plzeň",
            "Olomouc",
            "Liberec",
            "České Budějovice",
            "Hradec Králové",
            "Pardubice",
            "Zlín",
            "Jihlava",
            "Teplice",
        ],
    },
    NationDef {
        name: "Norway",
        power: 65,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Oslo",
            "Bergen",
            "Trondheim",
            "Stavanger",
            "Tromsø",
            "Drammen",
            "Kristiansand",
            "Ålesund",
            "Bodø",
            "Fredrikstad",
            "Hamar",
            "Moss",
        ],
    },
    NationDef {
        name: "Ukraine",
        power: 65,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Kyiv",
            "Kharkiv",
            "Odesa",
            "Dnipro",
            "Lviv",
            "Zaporizhzhia",
            "Donetsk",
            "Kryvyi Rih",
            "Mykolaiv",
            "Poltava",
            "Chernihiv",
            "Vinnytsia",
        ],
    },
    NationDef {
        name: "Serbia",
        power: 64,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Belgrade",
            "Novi Sad",
            "Niš",
            "Kragujevac",
            "Subotica",
            "Čačak",
            "Užice",
            "Valjevo",
            "Kraljevo",
            "Zrenjanin",
            "Pančevo",
            "Smederevo",
        ],
    },
    NationDef {
        name: "Ecuador",
        power: 62,
        divisions: T3_DIVS,
        style: Spanish,
        cities: &[
            "Quito",
            "Guayaquil",
            "Cuenca",
            "Ambato",
            "Manta",
            "Loja",
            "Riobamba",
            "Ibarra",
            "Portoviejo",
            "Machala",
            "Esmeraldas",
            "Latacunga",
        ],
    },
    NationDef {
        name: "Peru",
        power: 60,
        divisions: T3_DIVS,
        style: Spanish,
        cities: &[
            "Lima",
            "Arequipa",
            "Trujillo",
            "Cusco",
            "Chiclayo",
            "Piura",
            "Iquitos",
            "Huancayo",
            "Tacna",
            "Puno",
            "Ayacucho",
            "Cajamarca",
        ],
    },
    NationDef {
        name: "Paraguay",
        power: 58,
        divisions: T3_DIVS,
        style: Spanish,
        cities: &[
            "Asunción",
            "Encarnación",
            "Ciudad del Este",
            "San Lorenzo",
            "Luque",
            "Capiatá",
            "Lambaré",
            "Villarrica",
            "Coronel Oviedo",
            "Concepción",
            "Pilar",
            "Pedro Juan Caballero",
        ],
    },
    // ── Tier 5: developing football nations (48–64) ──────────────────────────
    NationDef {
        name: "Morocco",
        power: 64,
        divisions: T3_DIVS,
        style: French,
        cities: &[
            "Casablanca",
            "Rabat",
            "Marrakech",
            "Fès",
            "Tangier",
            "Agadir",
            "Meknès",
            "Oujda",
            "Kenitra",
            "Tétouan",
            "Safi",
            "Nador",
        ],
    },
    NationDef {
        name: "Nigeria",
        power: 62,
        divisions: T3_DIVS,
        style: English,
        cities: &[
            "Lagos",
            "Abuja",
            "Kano",
            "Ibadan",
            "Port Harcourt",
            "Enugu",
            "Kaduna",
            "Benin City",
            "Jos",
            "Ilorin",
            "Onitsha",
            "Warri",
        ],
    },
    NationDef {
        name: "Egypt",
        power: 60,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Cairo",
            "Alexandria",
            "Giza",
            "Port Said",
            "Suez",
            "Ismailia",
            "Luxor",
            "Aswan",
            "Mansoura",
            "Tanta",
            "Assiut",
            "Hurghada",
        ],
    },
    NationDef {
        name: "Saudi Arabia",
        power: 60,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Riyadh", "Jeddah", "Dammam", "Mecca", "Medina", "Khobar", "Abha", "Taif", "Tabuk",
            "Buraidah", "Hail", "Jubail",
        ],
    },
    NationDef {
        name: "Senegal",
        power: 60,
        divisions: T3_DIVS,
        style: French,
        cities: &[
            "Dakar",
            "Thiès",
            "Kaolack",
            "Saint-Louis",
            "Ziguinchor",
            "Rufisque",
            "Mbour",
            "Tambacounda",
            "Kolda",
            "Louga",
            "Diourbel",
            "Tivaouane",
        ],
    },
    NationDef {
        name: "Ivory Coast",
        power: 59,
        divisions: T3_DIVS,
        style: French,
        cities: &[
            "Abidjan",
            "Bouaké",
            "Yamoussoukro",
            "Daloa",
            "San-Pédro",
            "Korhogo",
            "Man",
            "Gagnoa",
            "Abengourou",
            "Bondoukou",
            "Grand-Bassam",
            "Divo",
        ],
    },
    NationDef {
        name: "Ghana",
        power: 58,
        divisions: T3_DIVS,
        style: English,
        cities: &[
            "Accra",
            "Kumasi",
            "Tamale",
            "Takoradi",
            "Cape Coast",
            "Sunyani",
            "Ho",
            "Koforidua",
            "Sekondi",
            "Tema",
            "Bolgatanga",
            "Wa",
        ],
    },
    NationDef {
        name: "Cameroon",
        power: 58,
        divisions: T3_DIVS,
        style: French,
        cities: &[
            "Douala",
            "Yaoundé",
            "Bafoussam",
            "Garoua",
            "Bamenda",
            "Limbe",
            "Ngaoundéré",
            "Kribi",
            "Buea",
            "Bertoua",
            "Ebolowa",
            "Maroua",
        ],
    },
    NationDef {
        name: "Algeria",
        power: 58,
        divisions: T3_DIVS,
        style: French,
        cities: &[
            "Algiers",
            "Oran",
            "Constantine",
            "Annaba",
            "Blida",
            "Sétif",
            "Batna",
            "Tlemcen",
            "Béjaïa",
            "Skikda",
            "Mostaganem",
            "Tizi Ouzou",
        ],
    },
    NationDef {
        name: "South Africa",
        power: 58,
        divisions: T3_DIVS,
        style: English,
        cities: &[
            "Johannesburg",
            "Cape Town",
            "Durban",
            "Pretoria",
            "Port Elizabeth",
            "Bloemfontein",
            "East London",
            "Pietermaritzburg",
            "Polokwane",
            "Nelspruit",
            "Kimberley",
            "Rustenburg",
        ],
    },
    NationDef {
        name: "Tunisia",
        power: 56,
        divisions: T3_DIVS,
        style: French,
        cities: &[
            "Tunis",
            "Sfax",
            "Sousse",
            "Bizerte",
            "Gabès",
            "Kairouan",
            "Monastir",
            "Nabeul",
            "Médenine",
            "Béja",
            "Gafsa",
            "Hammamet",
        ],
    },
    NationDef {
        name: "Australia",
        power: 56,
        divisions: T3_DIVS,
        style: English,
        cities: &[
            "Sydney",
            "Melbourne",
            "Brisbane",
            "Perth",
            "Adelaide",
            "Canberra",
            "Newcastle",
            "Wollongong",
            "Geelong",
            "Hobart",
            "Darwin",
            "Townsville",
        ],
    },
    NationDef {
        name: "Qatar",
        power: 55,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Doha",
            "Al Rayyan",
            "Al Wakrah",
            "Al Khor",
            "Lusail",
            "Mesaieed",
            "Dukhan",
            "Al Shamal",
            "Umm Salal",
            "Al Daayen",
            "Al Shahaniya",
            "Al Zubarah",
        ],
    },
    NationDef {
        name: "Canada",
        power: 55,
        divisions: T3_DIVS,
        style: English,
        cities: &[
            "Toronto",
            "Vancouver",
            "Montreal",
            "Calgary",
            "Ottawa",
            "Edmonton",
            "Winnipeg",
            "Quebec City",
            "Hamilton",
            "Halifax",
            "Victoria",
            "Regina",
        ],
    },
    NationDef {
        name: "China",
        power: 54,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Beijing",
            "Shanghai",
            "Guangzhou",
            "Shenzhen",
            "Chengdu",
            "Wuhan",
            "Tianjin",
            "Chongqing",
            "Nanjing",
            "Hangzhou",
            "Qingdao",
            "Dalian",
        ],
    },
    NationDef {
        name: "Thailand",
        power: 50,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Bangkok",
            "Chiang Mai",
            "Khon Kaen",
            "Pattaya",
            "Nakhon Ratchasima",
            "Phuket",
            "Udon Thani",
            "Hat Yai",
            "Chiang Rai",
            "Surat Thani",
            "Nakhon Si Thammarat",
            "Rayong",
        ],
    },
    NationDef {
        name: "Vietnam",
        power: 48,
        divisions: T3_DIVS,
        style: Generic,
        cities: &[
            "Hanoi",
            "Ho Chi Minh City",
            "Da Nang",
            "Hai Phong",
            "Can Tho",
            "Hue",
            "Nha Trang",
            "Vinh",
            "Quy Nhon",
            "Da Lat",
            "Vung Tau",
            "Nam Dinh",
        ],
    },
];

/// Club-name patterns per style. `{c}` is replaced by the city name.
pub fn patterns_for(style: NameStyle) -> &'static [&'static str] {
    match style {
        NameStyle::English => &[
            "{c} FC",
            "{c} United",
            "{c} City",
            "{c} Rovers",
            "{c} Wanderers",
            "{c} Athletic",
            "{c} Albion",
            "AFC {c}",
        ],
        NameStyle::Spanish => &[
            "{c} CF",
            "Real {c}",
            "Atlético {c}",
            "Deportivo {c}",
            "UD {c}",
            "{c} SC",
            "CD {c}",
            "{c} FC",
        ],
        NameStyle::Portuguese => &[
            "{c} FC",
            "SC {c}",
            "CD {c}",
            "{c} SC",
            "CF {c}",
            "União {c}",
            "Atlético {c}",
            "Real {c}",
        ],
        NameStyle::German => &[
            "FC {c}",
            "{c} SV",
            "SV {c}",
            "1. FC {c}",
            "{c} 05",
            "{c} 98",
            "VfB {c}",
            "SpVgg {c}",
        ],
        NameStyle::Italian => &[
            "AC {c}",
            "{c} Calcio",
            "AS {c}",
            "SS {c}",
            "{c} FC",
            "US {c}",
            "FC {c}",
            "{c} BC",
        ],
        NameStyle::French => &[
            "AS {c}",
            "FC {c}",
            "Olympique {c}",
            "{c} FC",
            "RC {c}",
            "Stade {c}",
            "US {c}",
            "SC {c}",
        ],
        NameStyle::Dutch => &[
            "FC {c}", "SV {c}", "VV {c}", "RK {c}", "{c} FC", "AFC {c}", "SC {c}", "{c} '05",
        ],
        NameStyle::Generic => &[
            "{c} FC",
            "FC {c}",
            "{c} United",
            "{c} City",
            "{c} SC",
            "SC {c}",
            "{c} Athletic",
            "CD {c}",
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nation_list_is_fifty_and_sane() {
        assert_eq!(NATIONS.len(), 50, "spec: exactly 50 nations");
        for n in NATIONS {
            assert!((1..=99).contains(&n.power), "{} power out of range", n.name);
            assert!(
                (3..=4).contains(&n.divisions),
                "{} divisions out of spec",
                n.name
            );
            let combos = n.cities.len() * patterns_for(n.style).len();
            assert!(
                combos >= n.divisions as usize * 16,
                "{} cannot name {} clubs from {} combos",
                n.name,
                n.divisions as usize * 16,
                combos
            );
        }
    }

    #[test]
    fn tiers_are_ordered() {
        // Tier anchors: every T1 nation out-powers every T3-and-below nation,
        // and every T1/T2 nation out-powers every T5 nation.
        let min_t1 = NATIONS[..5].iter().map(|n| n.power).min().unwrap();
        let max_t5 = NATIONS[33..].iter().map(|n| n.power).max().unwrap();
        assert!(
            min_t1 > max_t5,
            "weakest elite must out-power strongest minnow"
        );
    }
}
