// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `beat_to_dto`, `build_game_state`, `build_peers`, `current_week_has_pending_match`, `current_year`, `flashpoint_dtos`, `get_world`, `live_league_clubs`, `set_state`, `take_state`, `with_beat_lib`, `with_state_mut`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveMatchSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// All 14 roles for the creation screen's role picker.
Future<List<CreationRoleDto>> listRolesForCreation() =>
    RustLib.instance.api.crateApiListRolesForCreation();

/// True if a game is currently loaded in memory.
Future<bool> hasActiveGame() => RustLib.instance.api.crateApiHasActiveGame();

/// Load the beat library from a JSON string (call once at app start with the bundled asset).
Future<bool> loadBeatLibrary({required String json}) =>
    RustLib.instance.api.crateApiLoadBeatLibrary(json: json);

/// List all clubs across all divisions for the new-game picker.
Future<List<ClubDto>> listClubs() => RustLib.instance.api.crateApiListClubs();

/// Start a new game. Returns the initial game state snapshot.
///
/// `position` accepts the full 0..7 `PrimaryPosition` range (widened from the old 0..2
/// broad-family range — bible §4 revision, TASK-CORE-creation-role-choice): 0=ST, 1=W,
/// 2=WM, 3=CAM, 4=CM, 5=DM, 6=FB, 7=CB. Out-of-range values default to ST.
///
/// `lifestyle` is accepted only for FFI binary compatibility with the existing
/// `frb_generated.rs` signature — it is now ignored. Lifestyle is derived (bible
/// §8.5/§8.6) from training intensity, dev investment and sponsor choices over the
/// career; read it back via the `lifestyle` field on `GoatGameState`.
Future<GoatGameState> newGame(
        {required String playerName,
        required int position,
        required int clubId,
        required BigInt seed,
        required int lifestyle,
        int? primaryRole}) =>
    RustLib.instance.api.crateApiNewGame(
        playerName: playerName,
        position: position,
        clubId: clubId,
        seed: seed,
        lifestyle: lifestyle,
        primaryRole: primaryRole);

/// Advance one training week. Returns updated state.
Future<GoatGameState> advanceWeek() =>
    RustLib.instance.api.crateApiAdvanceWeek();

/// Advance up to `n` weeks, stopping at notable events.
///
/// Caps the actual number of weeks ticked to at most 1 while this week's
/// fixture(s) are unplayed (0 if this week's training is already done too) —
/// otherwise the player's age/development clock (ticked here) would drift
/// arbitrarily far ahead of the match calendar (only advanced by actually
/// playing), leaving fixtures stuck unplayed indefinitely with no way back.
/// A single extra tick is still allowed so this doesn't regress the ordinary
/// "train, then play this week's match" flow — only unbounded multi-week
/// skips past an unresolved fixture are blocked.
Future<GoatGameState> advanceWeeks({required int n}) =>
    RustLib.instance.api.crateApiAdvanceWeeks(n: n);

/// Set weekly training routine. `attr_ids` are AttrId discriminants (0..29).
Future<GoatGameState> setRoutine(
        {required List<int> attrIds, required int intensity}) =>
    RustLib.instance.api
        .crateApiSetRoutine(attrIds: attrIds, intensity: intensity);

/// Set the development-investment level (0..=3).
Future<GoatGameState> setDevInvestment({required int level}) =>
    RustLib.instance.api.crateApiSetDevInvestment(level: level);

/// Invest `amount` (£k) into the player's business.
Future<GoatGameState> investInBusiness({required PlatformInt64 amount}) =>
    RustLib.instance.api.crateApiInvestInBusiness(amount: amount);

/// Settle the season's economy (wage/bonus plus business swing), called at
/// season end. `season_bonus` is computed by the caller from the season's
/// outcome.
Future<GoatGameState> settleSeasonEconomy(
        {required PlatformInt64 seasonBonus}) =>
    RustLib.instance.api.crateApiSettleSeasonEconomy(seasonBonus: seasonBonus);

/// Set marketability (0–100) — gates which sponsor tiers are reachable.
Future<GoatGameState> setMarketability({required int value}) =>
    RustLib.instance.api.crateApiSetMarketability(value: value);

/// Sign a sponsor at `tier` (eligibility gated by marketability in the reducer).
Future<GoatGameState> signSponsor({required int tier}) =>
    RustLib.instance.api.crateApiSignSponsor(tier: tier);

/// Apply a life event to one relationship thread (0..=2) with the given delta.
Future<GoatGameState> applyLifeEvent(
        {required int thread, required int delta}) =>
    RustLib.instance.api.crateApiApplyLifeEvent(thread: thread, delta: delta);

/// Respond to a media flashpoint; `contrite` picks the tone (Character impact
/// lives in the reducer).
Future<GoatGameState> respondToMedia({required bool contrite}) =>
    RustLib.instance.api.crateApiRespondToMedia(contrite: contrite);

/// The backfilled historic canon, Ballon d'Or count first.
Future<List<PantheonEntryDto>> getPantheonCanon() =>
    RustLib.instance.api.crateApiGetPantheonCanon();

/// The emergent-rival verdict for the PC's generation — replays the cohort's
/// batch-tick up to the current season (same call shape the TUI's generation
/// screen uses).
Future<RivalVerdictDto> getRivalVerdict() =>
    RustLib.instance.api.crateApiGetRivalVerdict();

/// One summary line per league (champion + top scorer) for the current season
/// — the batch-tick summary view, D3-shaped (no raw population).
Future<List<LeagueSummaryDto>> getWorldStandings() =>
    RustLib.instance.api.crateApiGetWorldStandings();

/// Debug fingerprint of the loaded world (B.3) — a compact identity line a UI
/// can show in a debug corner to prove two saves share (or don't) a universe.
Future<String> getWorldFingerprint() =>
    RustLib.instance.api.crateApiGetWorldFingerprint();

/// Whether the PC must retire now (the hard age rule, bible §8.6).
Future<bool> shouldRetire() => RustLib.instance.api.crateApiShouldRetire();

/// The final verdict: every school's placement of the PC against the canon —
/// they disagree by design (bible §8.1). Built from the same LegacyEvidence +
/// axes + all_rankings pipeline the TUI's legacy screen uses.
Future<List<SchoolVerdictDto>> getFinalVerdict() =>
    RustLib.instance.api.crateApiGetFinalVerdict();

/// Auto-play or skip the current season round.
Future<(GoatGameState, MatchResultDto)> playRound(
        {required bool interactive}) =>
    RustLib.instance.api.crateApiPlayRound(interactive: interactive);

/// Get every fixture for the player's club across the full season, not just
/// the current calendar week. Fixture generation is deterministic and pure
/// (see `goat_world::fixtures` — "never stored, always recomputed"), so the
/// entire season's schedule already exists the moment a season starts; this
/// just exposes it instead of recomputing only the current week's slice.
Future<List<WeekFixtureDto>> getFullSeasonFixtures() =>
    RustLib.instance.api.crateApiGetFullSeasonFixtures();

/// Get the current league table.
Future<List<TableRowDto>> getTable() => RustLib.instance.api.crateApiGetTable();

/// Get all 30 attributes as DTOs.
Future<List<AttrDto>> getAttributes() =>
    RustLib.instance.api.crateApiGetAttributes();

/// Get family averages.
Future<FamilyDto> getFamilies() => RustLib.instance.api.crateApiGetFamilies();

/// Get all 14 roles sorted by rating.
Future<List<RoleDto>> getRoles() => RustLib.instance.api.crateApiGetRoles();

/// Get legacy axes and school rankings.
Future<LegacyDto> getLegacy() => RustLib.instance.api.crateApiGetLegacy();

/// Compute season awards (call after season ends).
Future<List<AwardDto>> getSeasonAwards() =>
    RustLib.instance.api.crateApiGetSeasonAwards();

/// Apply end-of-season legacy update (call after rendering awards).
Future<GoatGameState> applySeasonEnd() =>
    RustLib.instance.api.crateApiApplySeasonEnd();

/// Start the next season.
Future<GoatGameState> startNextSeason() =>
    RustLib.instance.api.crateApiStartNextSeason();

/// Accept a transfer offer identified by club_id.
Future<GoatGameState> acceptTransfer(
        {required int clubId,
        required PlatformInt64 wage,
        required int length}) =>
    RustLib.instance.api
        .crateApiAcceptTransfer(clubId: clubId, wage: wage, length: length);

/// Agitate for a transfer (advance power ladder, burn rep).
Future<GoatGameState> agitateForTransfer() =>
    RustLib.instance.api.crateApiAgitateForTransfer();

/// Generate transfer offers for the current window.
Future<List<TransferOfferDto>> getTransferOffers() =>
    RustLib.instance.api.crateApiGetTransferOffers();

/// Get all peers in the cohort.
Future<List<PeerDto>> getPeers() => RustLib.instance.api.crateApiGetPeers();

/// Retire the player.
Future<GoatGameState> retire() => RustLib.instance.api.crateApiRetire();

/// Save game to file at `path`.
Future<bool> saveGame({required String path}) =>
    RustLib.instance.api.crateApiSaveGame(path: path);

/// Load game from file at `path`.
Future<GoatGameState?> loadGame({required String path}) =>
    RustLib.instance.api.crateApiLoadGame(path: path);

/// Get a snapshot without mutating state.
Future<GoatGameState?> getState() => RustLib.instance.api.crateApiGetState();

/// Start an interactive match for the current season round.
/// Returns `None` if there is no fixture this round, or if the PC is
/// suspended — a suspended player doesn't personally take part (bible
/// AC-06); callers should fall back to `play_round`, which auto-sims the
/// club's match without the PC and serves one match of the ban.
Future<ActiveBeatDto?> startInteractiveMatch() =>
    RustLib.instance.api.crateApiStartInteractiveMatch();

/// Resolve a player choice for the current interactive match beat.
/// Returns `None` if no match is active.
Future<BeatOutcomeDto?> makeBeatChoice({required int choiceIdx}) =>
    RustLib.instance.api.crateApiMakeBeatChoice(choiceIdx: choiceIdx);

class ActiveBeatDto {
  final int beatId;
  final String setup;
  final List<BeatChoiceDto> choices;
  final int minute;
  final int playerOutput;
  final int goalsFor;
  final int goalsAgainst;
  final int stamina;
  final int beatNumber;
  final int totalBeats;
  final String oppName;

  const ActiveBeatDto({
    required this.beatId,
    required this.setup,
    required this.choices,
    required this.minute,
    required this.playerOutput,
    required this.goalsFor,
    required this.goalsAgainst,
    required this.stamina,
    required this.beatNumber,
    required this.totalBeats,
    required this.oppName,
  });

  @override
  int get hashCode =>
      beatId.hashCode ^
      setup.hashCode ^
      choices.hashCode ^
      minute.hashCode ^
      playerOutput.hashCode ^
      goalsFor.hashCode ^
      goalsAgainst.hashCode ^
      stamina.hashCode ^
      beatNumber.hashCode ^
      totalBeats.hashCode ^
      oppName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveBeatDto &&
          runtimeType == other.runtimeType &&
          beatId == other.beatId &&
          setup == other.setup &&
          choices == other.choices &&
          minute == other.minute &&
          playerOutput == other.playerOutput &&
          goalsFor == other.goalsFor &&
          goalsAgainst == other.goalsAgainst &&
          stamina == other.stamina &&
          beatNumber == other.beatNumber &&
          totalBeats == other.totalBeats &&
          oppName == other.oppName;
}

class AttrDto {
  final String name;
  final int current;
  final int potential;
  final String family;

  const AttrDto({
    required this.name,
    required this.current,
    required this.potential,
    required this.family,
  });

  @override
  int get hashCode =>
      name.hashCode ^ current.hashCode ^ potential.hashCode ^ family.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttrDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          current == other.current &&
          potential == other.potential &&
          family == other.family;
}

class AwardDto {
  final String awardName;
  final String winnerName;
  final String runnerUp;
  final bool pcWon;
  final int pcScore;
  final int winnerScore;

  const AwardDto({
    required this.awardName,
    required this.winnerName,
    required this.runnerUp,
    required this.pcWon,
    required this.pcScore,
    required this.winnerScore,
  });

  @override
  int get hashCode =>
      awardName.hashCode ^
      winnerName.hashCode ^
      runnerUp.hashCode ^
      pcWon.hashCode ^
      pcScore.hashCode ^
      winnerScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AwardDto &&
          runtimeType == other.runtimeType &&
          awardName == other.awardName &&
          winnerName == other.winnerName &&
          runnerUp == other.runnerUp &&
          pcWon == other.pcWon &&
          pcScore == other.pcScore &&
          winnerScore == other.winnerScore;
}

class BeatChoiceDto {
  final String text;
  final String primaryAttr;
  final int difficulty;

  const BeatChoiceDto({
    required this.text,
    required this.primaryAttr,
    required this.difficulty,
  });

  @override
  int get hashCode =>
      text.hashCode ^ primaryAttr.hashCode ^ difficulty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BeatChoiceDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          primaryAttr == other.primaryAttr &&
          difficulty == other.difficulty;
}

class BeatOutcomeDto {
  final bool success;
  final String outcomeText;
  final int outputDelta;
  final bool goalFor;
  final bool goalAgainst;
  final bool yellowCard;
  final bool redCard;
  final int playerOutput;
  final int goalsFor;
  final int goalsAgainst;
  final bool isComplete;
  final ActiveBeatDto? nextBeat;
  final MatchResultDto? finalResult;
  final GoatGameState? gameState;

  const BeatOutcomeDto({
    required this.success,
    required this.outcomeText,
    required this.outputDelta,
    required this.goalFor,
    required this.goalAgainst,
    required this.yellowCard,
    required this.redCard,
    required this.playerOutput,
    required this.goalsFor,
    required this.goalsAgainst,
    required this.isComplete,
    this.nextBeat,
    this.finalResult,
    this.gameState,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      outcomeText.hashCode ^
      outputDelta.hashCode ^
      goalFor.hashCode ^
      goalAgainst.hashCode ^
      yellowCard.hashCode ^
      redCard.hashCode ^
      playerOutput.hashCode ^
      goalsFor.hashCode ^
      goalsAgainst.hashCode ^
      isComplete.hashCode ^
      nextBeat.hashCode ^
      finalResult.hashCode ^
      gameState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BeatOutcomeDto &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          outcomeText == other.outcomeText &&
          outputDelta == other.outputDelta &&
          goalFor == other.goalFor &&
          goalAgainst == other.goalAgainst &&
          yellowCard == other.yellowCard &&
          redCard == other.redCard &&
          playerOutput == other.playerOutput &&
          goalsFor == other.goalsFor &&
          goalsAgainst == other.goalsAgainst &&
          isComplete == other.isComplete &&
          nextBeat == other.nextBeat &&
          finalResult == other.finalResult &&
          gameState == other.gameState;
}

class ClubDto {
  final int clubId;
  final String name;
  final int strength;
  final String divName;
  final int divIdx;

  const ClubDto({
    required this.clubId,
    required this.name,
    required this.strength,
    required this.divName,
    required this.divIdx,
  });

  @override
  int get hashCode =>
      clubId.hashCode ^
      name.hashCode ^
      strength.hashCode ^
      divName.hashCode ^
      divIdx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubDto &&
          runtimeType == other.runtimeType &&
          clubId == other.clubId &&
          name == other.name &&
          strength == other.strength &&
          divName == other.divName &&
          divIdx == other.divIdx;
}

/// Role metadata for the creation picker (TASK-CORE-creation-role-choice):
/// RoleId discriminant + display name + broad family.
class CreationRoleDto {
  final int roleId;
  final String name;

  /// 0=Defender 1=Midfielder 2=Forward.
  final int family;

  const CreationRoleDto({
    required this.roleId,
    required this.name,
    required this.family,
  });

  @override
  int get hashCode => roleId.hashCode ^ name.hashCode ^ family.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreationRoleDto &&
          runtimeType == other.runtimeType &&
          roleId == other.roleId &&
          name == other.name &&
          family == other.family;
}

class FamilyDto {
  final int pace;
  final int shooting;
  final int passing;
  final int dribbling;
  final int defending;
  final int physical;

  const FamilyDto({
    required this.pace,
    required this.shooting,
    required this.passing,
    required this.dribbling,
    required this.defending,
    required this.physical,
  });

  @override
  int get hashCode =>
      pace.hashCode ^
      shooting.hashCode ^
      passing.hashCode ^
      dribbling.hashCode ^
      defending.hashCode ^
      physical.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FamilyDto &&
          runtimeType == other.runtimeType &&
          pace == other.pace &&
          shooting == other.shooting &&
          passing == other.passing &&
          dribbling == other.dribbling &&
          defending == other.defending &&
          physical == other.physical;
}

/// A calendar-window opening surfaced during a week tick (B.2) — the UI shows
/// these as the week's interruptions. `window` is the WindowKind discriminant:
/// 0=TransferSummer 1=TransferWinter 2=InternationalBreak 3=OffSeason.
class FlashpointDto {
  final int day;
  final int window;
  final String label;

  const FlashpointDto({
    required this.day,
    required this.window,
    required this.label,
  });

  @override
  int get hashCode => day.hashCode ^ window.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlashpointDto &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          window == other.window &&
          label == other.label;
}

/// Flat snapshot of game state returned to Dart after every mutation.
class GoatGameState {
  final String playerName;
  final int ageYears;
  final int ageWeeksInYear;
  final int energy;
  final int ovr;
  final int injuryWeeks;

  /// PrimaryPosition discriminant: 0=ST 1=W 2=WM 3=CAM 4=CM 5=DM 6=FB 7=CB.
  final int position;
  final String clubName;
  final String divName;
  final String nationality;
  final int seasonNumber;
  final int seasonRound;
  final int roundsPerSeason;
  final int form;
  final int seasonGoals;
  final int seasonMatches;
  final bool isSuspended;
  final int contractSeasonsLeft;
  final PlatformInt64 wageAnnual;
  final PlatformInt64 savings;
  final int powerLadder;
  final PlatformInt64 businessValue;
  final bool bankrupt;
  final int devInvestLevel;
  final int marketability;
  final int sponsorTier;

  /// The three relationship threads' current scores.
  final Int32List relationships;
  final int yellowCardsSeason;
  final int disciplineRep;
  final int careerGoals;
  final int careerMatches;
  final int careerSeasons;
  final int leagueTitles;
  final int playerOfYearWins;
  final int sportingRep;
  final int clubFanRep;
  final int characterRep;
  final int lifestyle;
  final bool isRetired;
  final bool hasRival;
  final String rivalName;
  final int routineIntensity;
  final List<String> routineFocusAttrNames;
  final List<String> lastEvents;

  /// 0-indexed calendar week within the season (derived from season_round).
  final int calendarWeek;

  /// Total calendar weeks in a season (always SEASON_CALENDAR_WEEKS = 38).
  final int calendarWeeks;

  /// "Game Week 5 · Sep 2025"
  final String calendarWeekLabel;

  /// True if the current week is a break (no matches).
  final bool isBreakWeek;

  /// Matches scheduled for the current calendar week.
  final List<WeekFixtureDto> weekFixtures;

  /// How many of this week's matches have been played.
  final int weekFixturesPlayed;

  /// True if the player has used their training session this calendar week.
  final bool weekTrainingDone;

  /// Days since career start (drives the CalendarEngine week ticks).
  final int epochDay;

  /// Window-opening flashpoints accumulated by the most recent week tick.
  final List<FlashpointDto> lastFlashpoints;

  const GoatGameState({
    required this.playerName,
    required this.ageYears,
    required this.ageWeeksInYear,
    required this.energy,
    required this.ovr,
    required this.injuryWeeks,
    required this.position,
    required this.clubName,
    required this.divName,
    required this.nationality,
    required this.seasonNumber,
    required this.seasonRound,
    required this.roundsPerSeason,
    required this.form,
    required this.seasonGoals,
    required this.seasonMatches,
    required this.isSuspended,
    required this.contractSeasonsLeft,
    required this.wageAnnual,
    required this.savings,
    required this.powerLadder,
    required this.businessValue,
    required this.bankrupt,
    required this.devInvestLevel,
    required this.marketability,
    required this.sponsorTier,
    required this.relationships,
    required this.yellowCardsSeason,
    required this.disciplineRep,
    required this.careerGoals,
    required this.careerMatches,
    required this.careerSeasons,
    required this.leagueTitles,
    required this.playerOfYearWins,
    required this.sportingRep,
    required this.clubFanRep,
    required this.characterRep,
    required this.lifestyle,
    required this.isRetired,
    required this.hasRival,
    required this.rivalName,
    required this.routineIntensity,
    required this.routineFocusAttrNames,
    required this.lastEvents,
    required this.calendarWeek,
    required this.calendarWeeks,
    required this.calendarWeekLabel,
    required this.isBreakWeek,
    required this.weekFixtures,
    required this.weekFixturesPlayed,
    required this.weekTrainingDone,
    required this.epochDay,
    required this.lastFlashpoints,
  });

  @override
  int get hashCode =>
      playerName.hashCode ^
      ageYears.hashCode ^
      ageWeeksInYear.hashCode ^
      energy.hashCode ^
      ovr.hashCode ^
      injuryWeeks.hashCode ^
      position.hashCode ^
      clubName.hashCode ^
      divName.hashCode ^
      nationality.hashCode ^
      seasonNumber.hashCode ^
      seasonRound.hashCode ^
      roundsPerSeason.hashCode ^
      form.hashCode ^
      seasonGoals.hashCode ^
      seasonMatches.hashCode ^
      isSuspended.hashCode ^
      contractSeasonsLeft.hashCode ^
      wageAnnual.hashCode ^
      savings.hashCode ^
      powerLadder.hashCode ^
      businessValue.hashCode ^
      bankrupt.hashCode ^
      devInvestLevel.hashCode ^
      marketability.hashCode ^
      sponsorTier.hashCode ^
      relationships.hashCode ^
      yellowCardsSeason.hashCode ^
      disciplineRep.hashCode ^
      careerGoals.hashCode ^
      careerMatches.hashCode ^
      careerSeasons.hashCode ^
      leagueTitles.hashCode ^
      playerOfYearWins.hashCode ^
      sportingRep.hashCode ^
      clubFanRep.hashCode ^
      characterRep.hashCode ^
      lifestyle.hashCode ^
      isRetired.hashCode ^
      hasRival.hashCode ^
      rivalName.hashCode ^
      routineIntensity.hashCode ^
      routineFocusAttrNames.hashCode ^
      lastEvents.hashCode ^
      calendarWeek.hashCode ^
      calendarWeeks.hashCode ^
      calendarWeekLabel.hashCode ^
      isBreakWeek.hashCode ^
      weekFixtures.hashCode ^
      weekFixturesPlayed.hashCode ^
      weekTrainingDone.hashCode ^
      epochDay.hashCode ^
      lastFlashpoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GoatGameState &&
          runtimeType == other.runtimeType &&
          playerName == other.playerName &&
          ageYears == other.ageYears &&
          ageWeeksInYear == other.ageWeeksInYear &&
          energy == other.energy &&
          ovr == other.ovr &&
          injuryWeeks == other.injuryWeeks &&
          position == other.position &&
          clubName == other.clubName &&
          divName == other.divName &&
          nationality == other.nationality &&
          seasonNumber == other.seasonNumber &&
          seasonRound == other.seasonRound &&
          roundsPerSeason == other.roundsPerSeason &&
          form == other.form &&
          seasonGoals == other.seasonGoals &&
          seasonMatches == other.seasonMatches &&
          isSuspended == other.isSuspended &&
          contractSeasonsLeft == other.contractSeasonsLeft &&
          wageAnnual == other.wageAnnual &&
          savings == other.savings &&
          powerLadder == other.powerLadder &&
          businessValue == other.businessValue &&
          bankrupt == other.bankrupt &&
          devInvestLevel == other.devInvestLevel &&
          marketability == other.marketability &&
          sponsorTier == other.sponsorTier &&
          relationships == other.relationships &&
          yellowCardsSeason == other.yellowCardsSeason &&
          disciplineRep == other.disciplineRep &&
          careerGoals == other.careerGoals &&
          careerMatches == other.careerMatches &&
          careerSeasons == other.careerSeasons &&
          leagueTitles == other.leagueTitles &&
          playerOfYearWins == other.playerOfYearWins &&
          sportingRep == other.sportingRep &&
          clubFanRep == other.clubFanRep &&
          characterRep == other.characterRep &&
          lifestyle == other.lifestyle &&
          isRetired == other.isRetired &&
          hasRival == other.hasRival &&
          rivalName == other.rivalName &&
          routineIntensity == other.routineIntensity &&
          routineFocusAttrNames == other.routineFocusAttrNames &&
          lastEvents == other.lastEvents &&
          calendarWeek == other.calendarWeek &&
          calendarWeeks == other.calendarWeeks &&
          calendarWeekLabel == other.calendarWeekLabel &&
          isBreakWeek == other.isBreakWeek &&
          weekFixtures == other.weekFixtures &&
          weekFixturesPlayed == other.weekFixturesPlayed &&
          weekTrainingDone == other.weekTrainingDone &&
          epochDay == other.epochDay &&
          lastFlashpoints == other.lastFlashpoints;
}

class LeagueSummaryDto {
  final String leagueName;
  final String nationName;
  final int tier;
  final String champion;
  final String topScorer;
  final int topScorerGoals;

  const LeagueSummaryDto({
    required this.leagueName,
    required this.nationName,
    required this.tier,
    required this.champion,
    required this.topScorer,
    required this.topScorerGoals,
  });

  @override
  int get hashCode =>
      leagueName.hashCode ^
      nationName.hashCode ^
      tier.hashCode ^
      champion.hashCode ^
      topScorer.hashCode ^
      topScorerGoals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LeagueSummaryDto &&
          runtimeType == other.runtimeType &&
          leagueName == other.leagueName &&
          nationName == other.nationName &&
          tier == other.tier &&
          champion == other.champion &&
          topScorer == other.topScorer &&
          topScorerGoals == other.topScorerGoals;
}

class LegacyAxisDto {
  final String name;
  final int value;

  const LegacyAxisDto({
    required this.name,
    required this.value,
  });

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegacyAxisDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class LegacyDto {
  final List<LegacyAxisDto> axes;
  final List<SchoolRankingDto> rankings;
  final String reputationLabel;
  final int sportingRep;
  final int characterRep;
  final int clubFanRep;

  const LegacyDto({
    required this.axes,
    required this.rankings,
    required this.reputationLabel,
    required this.sportingRep,
    required this.characterRep,
    required this.clubFanRep,
  });

  @override
  int get hashCode =>
      axes.hashCode ^
      rankings.hashCode ^
      reputationLabel.hashCode ^
      sportingRep.hashCode ^
      characterRep.hashCode ^
      clubFanRep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegacyDto &&
          runtimeType == other.runtimeType &&
          axes == other.axes &&
          rankings == other.rankings &&
          reputationLabel == other.reputationLabel &&
          sportingRep == other.sportingRep &&
          characterRep == other.characterRep &&
          clubFanRep == other.clubFanRep;
}

class MatchResultDto {
  final int playerOutput;
  final int goalsFor;
  final int goalsAgainst;
  final String ratingLabel;
  final List<String> moments;
  final int yellowCards;
  final bool redCard;

  const MatchResultDto({
    required this.playerOutput,
    required this.goalsFor,
    required this.goalsAgainst,
    required this.ratingLabel,
    required this.moments,
    required this.yellowCards,
    required this.redCard,
  });

  @override
  int get hashCode =>
      playerOutput.hashCode ^
      goalsFor.hashCode ^
      goalsAgainst.hashCode ^
      ratingLabel.hashCode ^
      moments.hashCode ^
      yellowCards.hashCode ^
      redCard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchResultDto &&
          runtimeType == other.runtimeType &&
          playerOutput == other.playerOutput &&
          goalsFor == other.goalsFor &&
          goalsAgainst == other.goalsAgainst &&
          ratingLabel == other.ratingLabel &&
          moments == other.moments &&
          yellowCards == other.yellowCards &&
          redCard == other.redCard;
}

class PantheonEntryDto {
  final String name;
  final String nationName;
  final int debutYear;
  final int finalYear;
  final int peakOvr;
  final int ballonDors;

  const PantheonEntryDto({
    required this.name,
    required this.nationName,
    required this.debutYear,
    required this.finalYear,
    required this.peakOvr,
    required this.ballonDors,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      nationName.hashCode ^
      debutYear.hashCode ^
      finalYear.hashCode ^
      peakOvr.hashCode ^
      ballonDors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PantheonEntryDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          nationName == other.nationName &&
          debutYear == other.debutYear &&
          finalYear == other.finalYear &&
          peakOvr == other.peakOvr &&
          ballonDors == other.ballonDors;
}

class PeerDto {
  final String name;
  final String nationality;
  final int careerGoals;
  final int careerMatches;
  final int avgOutput;
  final int titles;
  final bool isRival;

  const PeerDto({
    required this.name,
    required this.nationality,
    required this.careerGoals,
    required this.careerMatches,
    required this.avgOutput,
    required this.titles,
    required this.isRival,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      nationality.hashCode ^
      careerGoals.hashCode ^
      careerMatches.hashCode ^
      avgOutput.hashCode ^
      titles.hashCode ^
      isRival.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          nationality == other.nationality &&
          careerGoals == other.careerGoals &&
          careerMatches == other.careerMatches &&
          avgOutput == other.avgOutput &&
          titles == other.titles &&
          isRival == other.isRival;
}

class RivalVerdictDto {
  final bool hasRival;
  final bool weakEra;
  final String name;
  final int peerGoals;
  final int peerTitles;

  const RivalVerdictDto({
    required this.hasRival,
    required this.weakEra,
    required this.name,
    required this.peerGoals,
    required this.peerTitles,
  });

  @override
  int get hashCode =>
      hasRival.hashCode ^
      weakEra.hashCode ^
      name.hashCode ^
      peerGoals.hashCode ^
      peerTitles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RivalVerdictDto &&
          runtimeType == other.runtimeType &&
          hasRival == other.hasRival &&
          weakEra == other.weakEra &&
          name == other.name &&
          peerGoals == other.peerGoals &&
          peerTitles == other.peerTitles;
}

class RoleDto {
  final String name;
  final int rating;
  final String familiarity;

  const RoleDto({
    required this.name,
    required this.rating,
    required this.familiarity,
  });

  @override
  int get hashCode => name.hashCode ^ rating.hashCode ^ familiarity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoleDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          rating == other.rating &&
          familiarity == other.familiarity;
}

class SchoolRankingDto {
  final String schoolName;
  final String schoolTagline;
  final int score;
  final int rank;
  final int total;

  const SchoolRankingDto({
    required this.schoolName,
    required this.schoolTagline,
    required this.score,
    required this.rank,
    required this.total,
  });

  @override
  int get hashCode =>
      schoolName.hashCode ^
      schoolTagline.hashCode ^
      score.hashCode ^
      rank.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SchoolRankingDto &&
          runtimeType == other.runtimeType &&
          schoolName == other.schoolName &&
          schoolTagline == other.schoolTagline &&
          score == other.score &&
          rank == other.rank &&
          total == other.total;
}

class SchoolVerdictDto {
  final String school;
  final int score;

  /// 1-based placement against the backfilled canon (1 = GOAT).
  final BigInt rank;

  const SchoolVerdictDto({
    required this.school,
    required this.score,
    required this.rank,
  });

  @override
  int get hashCode => school.hashCode ^ score.hashCode ^ rank.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SchoolVerdictDto &&
          runtimeType == other.runtimeType &&
          school == other.school &&
          score == other.score &&
          rank == other.rank;
}

class TableRowDto {
  final int position;
  final String clubName;
  final int played;
  final int won;
  final int drawn;
  final int lost;
  final int goalsFor;
  final int goalsAgainst;
  final int points;
  final bool isPlayerClub;

  const TableRowDto({
    required this.position,
    required this.clubName,
    required this.played,
    required this.won,
    required this.drawn,
    required this.lost,
    required this.goalsFor,
    required this.goalsAgainst,
    required this.points,
    required this.isPlayerClub,
  });

  @override
  int get hashCode =>
      position.hashCode ^
      clubName.hashCode ^
      played.hashCode ^
      won.hashCode ^
      drawn.hashCode ^
      lost.hashCode ^
      goalsFor.hashCode ^
      goalsAgainst.hashCode ^
      points.hashCode ^
      isPlayerClub.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableRowDto &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          clubName == other.clubName &&
          played == other.played &&
          won == other.won &&
          drawn == other.drawn &&
          lost == other.lost &&
          goalsFor == other.goalsFor &&
          goalsAgainst == other.goalsAgainst &&
          points == other.points &&
          isPlayerClub == other.isPlayerClub;
}

class TransferOfferDto {
  final int clubId;
  final String clubName;
  final String divName;
  final PlatformInt64 wage;
  final int length;
  final int strength;

  const TransferOfferDto({
    required this.clubId,
    required this.clubName,
    required this.divName,
    required this.wage,
    required this.length,
    required this.strength,
  });

  @override
  int get hashCode =>
      clubId.hashCode ^
      clubName.hashCode ^
      divName.hashCode ^
      wage.hashCode ^
      length.hashCode ^
      strength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferOfferDto &&
          runtimeType == other.runtimeType &&
          clubId == other.clubId &&
          clubName == other.clubName &&
          divName == other.divName &&
          wage == other.wage &&
          length == other.length &&
          strength == other.strength;
}

class WeekFixtureDto {
  /// 0-indexed round index.
  final int round;

  /// 0-indexed calendar week this round falls in (see goat_world::calendar).
  final int calendarWeek;
  final String opponent;
  final int oppStrength;
  final bool isHome;

  /// True if this round has already been played (round < season_round).
  final bool played;

  /// "Sat 16 Aug 2025"
  final String date;

  const WeekFixtureDto({
    required this.round,
    required this.calendarWeek,
    required this.opponent,
    required this.oppStrength,
    required this.isHome,
    required this.played,
    required this.date,
  });

  @override
  int get hashCode =>
      round.hashCode ^
      calendarWeek.hashCode ^
      opponent.hashCode ^
      oppStrength.hashCode ^
      isHome.hashCode ^
      played.hashCode ^
      date.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeekFixtureDto &&
          runtimeType == other.runtimeType &&
          round == other.round &&
          calendarWeek == other.calendarWeek &&
          opponent == other.opponent &&
          oppStrength == other.oppStrength &&
          isHome == other.isHome &&
          played == other.played &&
          date == other.date;
}
