// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveBeatDto dco_decode_active_beat_dto(dynamic raw);

  @protected
  AttrDto dco_decode_attr_dto(dynamic raw);

  @protected
  AwardDto dco_decode_award_dto(dynamic raw);

  @protected
  BeatChoiceDto dco_decode_beat_choice_dto(dynamic raw);

  @protected
  BeatOutcomeDto dco_decode_beat_outcome_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActiveBeatDto dco_decode_box_autoadd_active_beat_dto(dynamic raw);

  @protected
  BeatOutcomeDto dco_decode_box_autoadd_beat_outcome_dto(dynamic raw);

  @protected
  GoatGameState dco_decode_box_autoadd_goat_game_state(dynamic raw);

  @protected
  MatchResultDto dco_decode_box_autoadd_match_result_dto(dynamic raw);

  @protected
  ClubDto dco_decode_club_dto(dynamic raw);

  @protected
  FamilyDto dco_decode_family_dto(dynamic raw);

  @protected
  FlashpointDto dco_decode_flashpoint_dto(dynamic raw);

  @protected
  GoatGameState dco_decode_goat_game_state(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LeagueSummaryDto dco_decode_league_summary_dto(dynamic raw);

  @protected
  LegacyAxisDto dco_decode_legacy_axis_dto(dynamic raw);

  @protected
  LegacyDto dco_decode_legacy_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AttrDto> dco_decode_list_attr_dto(dynamic raw);

  @protected
  List<AwardDto> dco_decode_list_award_dto(dynamic raw);

  @protected
  List<BeatChoiceDto> dco_decode_list_beat_choice_dto(dynamic raw);

  @protected
  List<ClubDto> dco_decode_list_club_dto(dynamic raw);

  @protected
  List<FlashpointDto> dco_decode_list_flashpoint_dto(dynamic raw);

  @protected
  List<LeagueSummaryDto> dco_decode_list_league_summary_dto(dynamic raw);

  @protected
  List<LegacyAxisDto> dco_decode_list_legacy_axis_dto(dynamic raw);

  @protected
  List<PantheonEntryDto> dco_decode_list_pantheon_entry_dto(dynamic raw);

  @protected
  List<PeerDto> dco_decode_list_peer_dto(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoleDto> dco_decode_list_role_dto(dynamic raw);

  @protected
  List<SchoolRankingDto> dco_decode_list_school_ranking_dto(dynamic raw);

  @protected
  List<SchoolVerdictDto> dco_decode_list_school_verdict_dto(dynamic raw);

  @protected
  List<TableRowDto> dco_decode_list_table_row_dto(dynamic raw);

  @protected
  List<TransferOfferDto> dco_decode_list_transfer_offer_dto(dynamic raw);

  @protected
  List<WeekFixtureDto> dco_decode_list_week_fixture_dto(dynamic raw);

  @protected
  MatchResultDto dco_decode_match_result_dto(dynamic raw);

  @protected
  ActiveBeatDto? dco_decode_opt_box_autoadd_active_beat_dto(dynamic raw);

  @protected
  BeatOutcomeDto? dco_decode_opt_box_autoadd_beat_outcome_dto(dynamic raw);

  @protected
  GoatGameState? dco_decode_opt_box_autoadd_goat_game_state(dynamic raw);

  @protected
  MatchResultDto? dco_decode_opt_box_autoadd_match_result_dto(dynamic raw);

  @protected
  PantheonEntryDto dco_decode_pantheon_entry_dto(dynamic raw);

  @protected
  PeerDto dco_decode_peer_dto(dynamic raw);

  @protected
  (GoatGameState, MatchResultDto)
      dco_decode_record_goat_game_state_match_result_dto(dynamic raw);

  @protected
  RivalVerdictDto dco_decode_rival_verdict_dto(dynamic raw);

  @protected
  RoleDto dco_decode_role_dto(dynamic raw);

  @protected
  SchoolRankingDto dco_decode_school_ranking_dto(dynamic raw);

  @protected
  SchoolVerdictDto dco_decode_school_verdict_dto(dynamic raw);

  @protected
  TableRowDto dco_decode_table_row_dto(dynamic raw);

  @protected
  TransferOfferDto dco_decode_transfer_offer_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WeekFixtureDto dco_decode_week_fixture_dto(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveBeatDto sse_decode_active_beat_dto(SseDeserializer deserializer);

  @protected
  AttrDto sse_decode_attr_dto(SseDeserializer deserializer);

  @protected
  AwardDto sse_decode_award_dto(SseDeserializer deserializer);

  @protected
  BeatChoiceDto sse_decode_beat_choice_dto(SseDeserializer deserializer);

  @protected
  BeatOutcomeDto sse_decode_beat_outcome_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActiveBeatDto sse_decode_box_autoadd_active_beat_dto(
      SseDeserializer deserializer);

  @protected
  BeatOutcomeDto sse_decode_box_autoadd_beat_outcome_dto(
      SseDeserializer deserializer);

  @protected
  GoatGameState sse_decode_box_autoadd_goat_game_state(
      SseDeserializer deserializer);

  @protected
  MatchResultDto sse_decode_box_autoadd_match_result_dto(
      SseDeserializer deserializer);

  @protected
  ClubDto sse_decode_club_dto(SseDeserializer deserializer);

  @protected
  FamilyDto sse_decode_family_dto(SseDeserializer deserializer);

  @protected
  FlashpointDto sse_decode_flashpoint_dto(SseDeserializer deserializer);

  @protected
  GoatGameState sse_decode_goat_game_state(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LeagueSummaryDto sse_decode_league_summary_dto(SseDeserializer deserializer);

  @protected
  LegacyAxisDto sse_decode_legacy_axis_dto(SseDeserializer deserializer);

  @protected
  LegacyDto sse_decode_legacy_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AttrDto> sse_decode_list_attr_dto(SseDeserializer deserializer);

  @protected
  List<AwardDto> sse_decode_list_award_dto(SseDeserializer deserializer);

  @protected
  List<BeatChoiceDto> sse_decode_list_beat_choice_dto(
      SseDeserializer deserializer);

  @protected
  List<ClubDto> sse_decode_list_club_dto(SseDeserializer deserializer);

  @protected
  List<FlashpointDto> sse_decode_list_flashpoint_dto(
      SseDeserializer deserializer);

  @protected
  List<LeagueSummaryDto> sse_decode_list_league_summary_dto(
      SseDeserializer deserializer);

  @protected
  List<LegacyAxisDto> sse_decode_list_legacy_axis_dto(
      SseDeserializer deserializer);

  @protected
  List<PantheonEntryDto> sse_decode_list_pantheon_entry_dto(
      SseDeserializer deserializer);

  @protected
  List<PeerDto> sse_decode_list_peer_dto(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoleDto> sse_decode_list_role_dto(SseDeserializer deserializer);

  @protected
  List<SchoolRankingDto> sse_decode_list_school_ranking_dto(
      SseDeserializer deserializer);

  @protected
  List<SchoolVerdictDto> sse_decode_list_school_verdict_dto(
      SseDeserializer deserializer);

  @protected
  List<TableRowDto> sse_decode_list_table_row_dto(SseDeserializer deserializer);

  @protected
  List<TransferOfferDto> sse_decode_list_transfer_offer_dto(
      SseDeserializer deserializer);

  @protected
  List<WeekFixtureDto> sse_decode_list_week_fixture_dto(
      SseDeserializer deserializer);

  @protected
  MatchResultDto sse_decode_match_result_dto(SseDeserializer deserializer);

  @protected
  ActiveBeatDto? sse_decode_opt_box_autoadd_active_beat_dto(
      SseDeserializer deserializer);

  @protected
  BeatOutcomeDto? sse_decode_opt_box_autoadd_beat_outcome_dto(
      SseDeserializer deserializer);

  @protected
  GoatGameState? sse_decode_opt_box_autoadd_goat_game_state(
      SseDeserializer deserializer);

  @protected
  MatchResultDto? sse_decode_opt_box_autoadd_match_result_dto(
      SseDeserializer deserializer);

  @protected
  PantheonEntryDto sse_decode_pantheon_entry_dto(SseDeserializer deserializer);

  @protected
  PeerDto sse_decode_peer_dto(SseDeserializer deserializer);

  @protected
  (GoatGameState, MatchResultDto)
      sse_decode_record_goat_game_state_match_result_dto(
          SseDeserializer deserializer);

  @protected
  RivalVerdictDto sse_decode_rival_verdict_dto(SseDeserializer deserializer);

  @protected
  RoleDto sse_decode_role_dto(SseDeserializer deserializer);

  @protected
  SchoolRankingDto sse_decode_school_ranking_dto(SseDeserializer deserializer);

  @protected
  SchoolVerdictDto sse_decode_school_verdict_dto(SseDeserializer deserializer);

  @protected
  TableRowDto sse_decode_table_row_dto(SseDeserializer deserializer);

  @protected
  TransferOfferDto sse_decode_transfer_offer_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WeekFixtureDto sse_decode_week_fixture_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_beat_dto(ActiveBeatDto self, SseSerializer serializer);

  @protected
  void sse_encode_attr_dto(AttrDto self, SseSerializer serializer);

  @protected
  void sse_encode_award_dto(AwardDto self, SseSerializer serializer);

  @protected
  void sse_encode_beat_choice_dto(BeatChoiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_beat_outcome_dto(
      BeatOutcomeDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_active_beat_dto(
      ActiveBeatDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_beat_outcome_dto(
      BeatOutcomeDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_goat_game_state(
      GoatGameState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_match_result_dto(
      MatchResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_club_dto(ClubDto self, SseSerializer serializer);

  @protected
  void sse_encode_family_dto(FamilyDto self, SseSerializer serializer);

  @protected
  void sse_encode_flashpoint_dto(FlashpointDto self, SseSerializer serializer);

  @protected
  void sse_encode_goat_game_state(GoatGameState self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_league_summary_dto(
      LeagueSummaryDto self, SseSerializer serializer);

  @protected
  void sse_encode_legacy_axis_dto(LegacyAxisDto self, SseSerializer serializer);

  @protected
  void sse_encode_legacy_dto(LegacyDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_attr_dto(List<AttrDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_award_dto(List<AwardDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_beat_choice_dto(
      List<BeatChoiceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_club_dto(List<ClubDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_flashpoint_dto(
      List<FlashpointDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_league_summary_dto(
      List<LeagueSummaryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_legacy_axis_dto(
      List<LegacyAxisDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pantheon_entry_dto(
      List<PantheonEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_peer_dto(List<PeerDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_strict(
      Int32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_role_dto(List<RoleDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_school_ranking_dto(
      List<SchoolRankingDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_school_verdict_dto(
      List<SchoolVerdictDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_table_row_dto(
      List<TableRowDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_transfer_offer_dto(
      List<TransferOfferDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_week_fixture_dto(
      List<WeekFixtureDto> self, SseSerializer serializer);

  @protected
  void sse_encode_match_result_dto(
      MatchResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_active_beat_dto(
      ActiveBeatDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_beat_outcome_dto(
      BeatOutcomeDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_goat_game_state(
      GoatGameState? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_match_result_dto(
      MatchResultDto? self, SseSerializer serializer);

  @protected
  void sse_encode_pantheon_entry_dto(
      PantheonEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_peer_dto(PeerDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_goat_game_state_match_result_dto(
      (GoatGameState, MatchResultDto) self, SseSerializer serializer);

  @protected
  void sse_encode_rival_verdict_dto(
      RivalVerdictDto self, SseSerializer serializer);

  @protected
  void sse_encode_role_dto(RoleDto self, SseSerializer serializer);

  @protected
  void sse_encode_school_ranking_dto(
      SchoolRankingDto self, SseSerializer serializer);

  @protected
  void sse_encode_school_verdict_dto(
      SchoolVerdictDto self, SseSerializer serializer);

  @protected
  void sse_encode_table_row_dto(TableRowDto self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_offer_dto(
      TransferOfferDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_week_fixture_dto(
      WeekFixtureDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
