[package]
name = "goat-save"
version.workspace = true
edition.workspace = true

[dependencies]
goat-rng      = { path = "../goat-rng"      }
goat-fixed    = { path = "../goat-fixed"    }
goat-core     = { path = "../goat-core"     }
goat-world    = { path = "../goat-world"    }
goat-calendar = { path = "../goat-calendar" }
