//! Canonical dated tournament progress; renderers never own brackets or outcomes.
use crate::discipline::NpcCardEvent;

pub const LEAGUE: u32 = 1;
pub const DOMESTIC: u32 = 2;
pub const FRIENDLY: u32 = 8;
pub const EXTRA_ROUND: u32 = 0x8000_0000;
pub const MIN_REST_DAYS: u32 = 3;

/// Participants are club ids, or nation ids for competition 6/7.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DatedFixture {
    pub id: u64,
    /// Legacy planned load identity for leagues, unique fixture identity otherwise.
    pub workload_id: u64,
    pub season: u32,
    pub competition: u32,
    pub region: u32,
    pub round: u32,
    pub slot: u32,
    pub stage: u8,
    pub leg: u8,
    pub original_day: u32,
    pub day: u32,
    pub home: u32,
    pub away: u32,
    pub priority: u8,
}
impl DatedFixture {
    pub fn national(&self) -> bool {
        matches!(self.competition, 6 | 7 | 9)
    }
    pub fn record_round(&self) -> u32 {
        if self.competition == LEAGUE {
            self.round
        } else {
            EXTRA_ROUND | (self.day << 8) | self.slot
        }
    }
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FixtureResult {
    pub fixture: DatedFixture,
    pub goals: [u32; 2],
    /// Knockout advancement winner; two-leg aggregate is decided after the return.
    /// Regulation goals remain unchanged, including when a shootout is required.
    pub winner: Option<u32>,
    pub detailed: bool,
}
/// phase 0 = groups/qualifying; 1 = knockout; 2 = complete.
/// kind 0 = domestic, 1 = continental club, 2 = national qualifying, 3 = finals.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Tournament {
    pub season: u32,
    pub competition: u32,
    pub region: u32,
    pub kind: u8,
    pub phase: u8,
    pub round: u32,
    pub participants: Vec<u32>,
    pub groups: Vec<Vec<u32>>,
    pub alive: Vec<u32>,
    pub fixture_ids: Vec<u64>,
    pub champion: Option<u32>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CoefficientYear {
    pub season: u32,
    pub points: Vec<u32>,
    pub entrants: Vec<u32>,
}
/// Pending fixtures and tournament state survive the June/July boundary.
#[derive(Clone, Default, Debug, PartialEq, Eq)]
pub struct CompetitionCalendar {
    pub prepared_through: u32,
    pub resolved_day: u32,
    pub fixtures: Vec<DatedFixture>,
    pub results: Vec<FixtureResult>,
    pub tournaments: Vec<Tournament>,
    pub coefficients: Vec<CoefficientYear>,
    pub pc_cards: Vec<NpcCardEvent>,
    pub pc_played_fixture_ids: Vec<u64>,
    /// Fresh SIM15 careers use dated markets; migrated SIM14 retains annual rosters.
    pub market_enabled: bool,
    pub pc_affiliations: Vec<(u32, u16)>,
    pub pc_contract_end: Option<u32>,
}
/// Explicit, renderer-independent input for legal named match squads.
#[derive(Clone, Debug)]
pub struct RosterPlayer {
    pub id: u32,
    pub name: String,
    pub attrs: [goat_fixed::Fixed; crate::attrs::NUM_ATTRS],
    pub position: u8,
    pub keeper: bool,
    pub rating: u8,
    pub form: i32,
    pub keeping: u8,
    pub energy: u8,
    pub aggression: u8,
    pub returning: bool,
    pub banned: bool,
}
#[derive(Clone, Debug)]
pub struct MatchRoster {
    pub profiles: [crate::tactical::TacticalProfile; 2],
    pub pc_side: Option<u8>,
    pub pc_position: u8,
    pub pc_rating: u8,
    pub pc_energy: u8,
    pub pc_returning: bool,
    pub pc_eligible: bool,
    pub fixture: DatedFixture,
    pub teams: [Vec<RosterPlayer>; 2],
    pub cards: Vec<NpcCardEvent>,
}

/// Finalized PC match bookkeeping. Generated by the match adapter, committed by core.
#[derive(Clone, Debug)]
pub struct DatedMatchReceipt {
    pub result: FixtureResult,
    pub credits: Vec<crate::state::NpcMatchCredit>,
    pub loads: Vec<crate::history::NpcMatchLoad>,
    pub cards: Vec<NpcCardEvent>,
    pub pc_cards: Vec<NpcCardEvent>,
    pub pc_goals: u32,
    pub pc_assists: u32,
    pub pc_output: i32,
    pub pc_minutes: u32,
    pub familiarity_xp: [goat_fixed::Fixed; crate::roles::NUM_ROLES],
    pub decisive: u32,
    pub clutch: u32,
}
